#goal definition: amplitude, frequency and number of cycles
float64 amplitude
float64 frequency
int32 cycles
---
#result definition: goal succeeded
int32[] sequence
---
#feedback definition: 
int32[] sequence
